name = "TapirBenchmarks"
uuid = "30ca4be2-9ad8-4bfe-aa9c-6e02d5a5fa22"
authors = ["Takafumi Arakaki <aka.tkf@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
